<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CurrentNamespace" Id="{2fd6ba25-d26d-4239-a1f1-e927ba32b15c}" SpecialFunc="None">
    <Declaration><![CDATA[(*
SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
SPDX-License-Identifier: MIT
License: https://opensource.org/license/mit
*)

{attribute 'no_explicit_call' := 'do not call this POU directly'}
PROGRAM INTERNAL CurrentNamespace
VAR
	{attribute 'hide'} 
	_NamespaceExtractor : NamespaceExtractor;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{e056e449-2e5f-43ff-85cc-c31271f3cdcd}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
PROPERTY Name : REFERENCE TO STRING]]></Declaration>
      <Get Name="Get" Id="{dfe8c12a-dc3c-4c40-a563-7e4381a8857f}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name REF= _NamespaceExtractor.CurrentNamespace;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>