<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="MAIN" Id="{e4eb2eaa-3c4c-0200-2bd5-f94fd2ee20dd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	
	automationRunner : TestAutomationRunner;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// automationRunner.TestAutomationUnits used as temporary solution while compiler bug with generics not fixed
automationRunner.Run(automationRunner.TestAutomationUnits);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>