<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="OpenFremwork_TestRunner" Id="{e4eb2eaa-3c4c-0200-2bd5-f94fd2ee20dd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM OpenFremwork_TestRunner
VAR
	testAutomationUnit : TestAutomationUnit;
	automationUnits : ARRAY [0..0] OF AutomationEngine.IAutomationUnit := [testAutomationUnit];
	
	automationRunner :  AutomationEngine.AutomationRunner;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[automationRunner.Run(automationUnits);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>