<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="AutoDisposeRegistrar" Id="{adc30d93-a416-4e9c-ba4d-f222a8683cc4}" SpecialFunc="None">
    <Declaration><![CDATA[// create instance of this class in any class with can be dynamically created with __NEW and should be automatically deleted with __DETETE
FUNCTION_BLOCK FINAL AutoDisposeRegistrar]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{4494557e-6055-4759-a72c-c44bdd5e675b}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)
	autoDisposedObject : IObject;   
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF autoDisposedObject <> 0 THEN
	DynamicMemoryManager.RegisterAutoDisposedObject(autoDisposedObject);
END_IF]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>