<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="NamespaceExtractor" Id="{775a0944-5518-486b-9fd6-59adf0116bbf}" SpecialFunc="None">
    <Declaration><![CDATA[(*
SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
SPDX-License-Identifier: MIT
License: https://opensource.org/license/mit
*)

FUNCTION_BLOCK INTERNAL NamespaceExtractor
VAR_OUTPUT
	{attribute 'init_namespace'} 
	CurrentNamespace : STRING; 	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>