<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="NamespaceExtractor" Id="{78607e67-960d-41c3-853a-302a53452c5c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL NamespaceExtractor
VAR_OUTPUT
	{attribute 'init_namespace'} 
	CurrentNamespace : STRING(255);	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>