<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="NamespaceExtractor" Id="{9d339231-03a2-46ce-ab0e-cb3efcc8e414}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL NamespaceExtractor
VAR_OUTPUT
	{attribute 'init_namespace'} 
	CurrentNamespace : STRING(255);	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>