<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CurrentNamespace" Id="{3d358878-e58a-48fc-b41d-ea218a9e3a9b}" SpecialFunc="None">
    <Declaration><![CDATA[(*
SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
SPDX-License-Identifier: MIT
License: https://opensource.org/license/mit
*)

{attribute 'no_explicit_call' := 'do not call this POU directly'}
PROGRAM INTERNAL CurrentNamespace
VAR
	{attribute 'hide'} 
	_NamespaceExtractor : NamespaceExtractor;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{7cbbb419-2ca8-4daf-a0f2-920d8419554e}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
PROPERTY Name : REFERENCE TO STRING]]></Declaration>
      <Get Name="Get" Id="{50d77bfb-1d4f-44a3-b3a6-73039375ff9c}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name REF= _NamespaceExtractor.CurrentNamespace;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>