<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="GenericValueHelper" Id="{632192a8-a1bb-419c-8eaa-096811803723}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM GenericValueHelper]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CheckIsNull" Id="{a4b85fbd-3ab9-4498-9490-7c058ad28188}">
      <Declaration><![CDATA[METHOD CheckIsNull : BOOL
VAR_INPUT
	value : GENERIC_VALUE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CheckIsNull := value.Address = 0 OR_ELSE value.Size = 0 OR_ELSE value.TypeClass = __SYSTEM.TYPE_CLASS.TYPE_NONE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>