<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TerminalModels" Id="{a98d253d-f32d-4c19-9c5a-20b1f705b795}" SpecialFunc="None">
    <Declaration><![CDATA[(*
SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
SPDX-License-Identifier: MIT
License: https://opensource.org/license/mit
*)

{attribute 'no_explicit_call' := 'do not call this function block directly'} 
PROGRAM TerminalModels
VAR_OUTPUT
	DI_1 : TOF_IOModels.EL1018;
	DO_2 : TOF_IOModels.EL2409;
	AI_3 : TOF_IOModels.EL3001;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>