<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="AutoDisposeRegistrar" Id="{adc30d93-a416-4e9c-ba4d-f222a8683cc4}" SpecialFunc="None">
    <Declaration><![CDATA[(*
SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
SPDX-License-Identifier: MIT
License: https://opensource.org/license/mit
*)

(*!
<summary>Include this registrar in an object that should be automatically deleted when dynamically created.</summary>
<description>
A successfully registered object is owned exclusively by DynamicMemoryManager until cleanup.
Other references are borrowed: do not delete the object manually or transfer its ownership.
Do not create objects with this registrar during DynamicMemoryManager cleanup callbacks.
</description>
*)

FUNCTION_BLOCK FINAL AutoDisposeRegistrar]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{4494557e-6055-4759-a72c-c44bdd5e675b}">
      <Declaration><![CDATA[(*!
<summary>FB_Init is always available implicitly and it is used primarily for initialization.</summary>
<description>
The return value is not evaluated. For a specific influence, you can also declare the
methods explicitly and provide additional code there with the standard initialization
code. You can evaluate the return value.
</description>
*)

//!<param name="bInitRetains">TRUE: the retain variables are initialized (reset warm / reset cold)</param>

//!<param name="bInCopyCode">TRUE: the instance will be copied to the copy code afterward (online change)</param>

METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; 
    bInCopyCode: BOOL;  
	autoDisposedObject : IObject;   
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF autoDisposedObject <> 0 THEN
	DynamicMemoryManager.RegisterAutoDisposedObject(autoDisposedObject);
END_IF]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>