<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="NamespaceExtractor" Id="{ec6d51c5-289a-48c0-9421-d9f46a88f34e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL NamespaceExtractor
VAR_OUTPUT
	{attribute 'init_namespace'} 
	CurrentNamespace : STRING(255);	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>