<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="AutomationUnit" Id="{715bcab9-6d21-43bf-ac33-fb2affdac1da}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT AutomationUnit EXTENDS TwinCAT_OpenFramework_Core.Object IMPLEMENTS IAutomationUnit]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="EmergencyStopRequest" Id="{608fa160-a1ee-4b42-a40b-f54246a9eaa1}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
PROPERTY EmergencyStopRequest : BOOL]]></Declaration>
      <Get Name="Get" Id="{ea1fec94-0a94-4c91-97a8-b829d143d2d9}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[EmergencyStopRequest := FALSE;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="EmergncyStop" Id="{ef005615-2d66-46a1-8783-315700ef3d6a}">
      <Declaration><![CDATA[METHOD EmergncyStop]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="HandleFault" Id="{5df2316a-8fd1-40c4-8c74-2bd8dd1e2dbf}">
      <Declaration><![CDATA[METHOD HandleFault]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Initialize" Id="{1b5cfeb5-a4c4-49db-8b34-eb001c2926ca}">
      <Declaration><![CDATA[METHOD Initialize : BOOL]]></Declaration>
      <Implementation>
        <ST><![CDATA[Initialize := TRUE;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Run" Id="{edf960fe-6c94-4ace-a7be-524e71aafd2a}">
      <Declaration><![CDATA[METHOD ABSTRACT Run]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>