<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SimpleDevice" Id="{7c21300f-1ad4-4217-9d49-d0f060249ecb}" SpecialFunc="None">
    <Declaration><![CDATA[(*

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
| SPDX-License-Identifier: LGPL-3.0-only
| For details check: LGPL-3.0-only_

.. _LGPL-3.0-only: https://www.gnu.org/licenses/lgpl-3.0.en.html

.. </legal notes>

*)

FUNCTION_BLOCK ABSTRACT SimpleDevice EXTENDS Device]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Overriden members" Id="{185562e6-4d51-4174-9462-636590f15fda}" />
    <Property Name="InternalChildCount" Id="{2fd0f5c0-dd77-4f98-b857-5fe55eabb827}" FolderPath="Overriden members\">
      <Declaration><![CDATA[PROPERTY PROTECTED FINAL InternalChildCount : Core.INT_INDEX]]></Declaration>
      <Get Name="Get" Id="{291f62b5-aa6f-4982-aecf-8050bd9a9e61}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[InternalChildCount := 0;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="InternalTryGetChildByIndex" Id="{20c59d36-ccf0-4a7d-bcde-dac491881353}" FolderPath="Overriden members\">
      <Declaration><![CDATA[METHOD PROTECTED InternalTryGetChildByIndex : IChildAutomationComponent
VAR_INPUT
	index : Core.INT_INDEX;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[InternalTryGetChildByIndex := 0;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>