<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{ca65afb8-727d-41a0-9d5d-3e437a913e63}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	AutomationRunner : SignalControlledIntersectionAutomationRunner;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AutomationRunner.Run();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>