<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="NamespaceExtractor" Id="{82c7e191-5376-479e-8d26-7381e8fb28dd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL NamespaceExtractor
VAR_OUTPUT
	{attribute 'init_namespace'} 
	CurrentNamespace : STRING(255);	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>