<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CurrentNamespace" Id="{d326d085-4c96-43f5-a212-89329b4d09f9}" SpecialFunc="None">
    <Declaration><![CDATA[(*
SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
SPDX-License-Identifier: MIT
License: https://opensource.org/license/mit
*)

{attribute 'no_explicit_call' := 'do not call this POU directly'}
PROGRAM INTERNAL CurrentNamespace
VAR
	{attribute 'hide'} 
	_NamespaceExtractor : NamespaceExtractor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{8f04ec1a-926d-4d00-b5c9-a6ab7edcc246}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
PROPERTY Name : REFERENCE TO STRING]]></Declaration>
      <Get Name="Get" Id="{1a5a14b1-e1b1-4028-ad25-6a65e10c43cf}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name REF= _NamespaceExtractor.CurrentNamespace;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>