<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="InputDevice" Id="{efa8b231-2751-492d-8626-738af2170475}" SpecialFunc="None">
    <Declaration><![CDATA[(*

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
| SPDX-License-Identifier: LGPL-3.0-only
| For details check: LGPL-3.0-only_

.. _LGPL-3.0-only: https://www.gnu.org/licenses/lgpl-3.0.en.html

.. </legal notes>

*)

FUNCTION_BLOCK ABSTRACT InputDevice EXTENDS Device IMPLEMENTS IInputDevice]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods to override" Id="{57e5027c-d025-4d1f-bcea-3cc2ecc52027}" />
    <Method Name="OnProcessInput" Id="{30690d44-71d9-48d1-97f7-67db91fa17cb}" FolderPath="Methods to override\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT OnProcessInput]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ProcessInput" Id="{c8983ed6-ea33-4eb7-a3f3-5a36dc5ceb9e}">
      <Declaration><![CDATA[METHOD FINAL ProcessInput]]></Declaration>
      <Implementation>
        <ST><![CDATA[OnProcessInput();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>