<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="InputOutputDevice" Id="{d3cfaf06-a014-47b7-8cf6-98a0cc083f94}" SpecialFunc="None">
    <Declaration><![CDATA[(*

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
| SPDX-License-Identifier: LGPL-3.0-only
| For details check: LGPL-3.0-only_

.. _LGPL-3.0-only: https://www.gnu.org/licenses/lgpl-3.0.en.html

.. </legal notes>

*)

FUNCTION_BLOCK ABSTRACT InputOutputDevice EXTENDS Device IMPLEMENTS IInputDevice, IOutputDevice]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods to override" Id="{c65c0bbf-e1ef-43ca-a18f-3c425c65c3bc}" />
    <Method Name="OnProcessInput" Id="{94e71efd-bb71-4095-9cb0-5f4f8a38c0d8}" FolderPath="Methods to override\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT OnProcessInput]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnProcessOutput" Id="{6751103a-6dfb-417d-8b22-87cbdffa3af8}" FolderPath="Methods to override\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT OnProcessOutput]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ProcessInput" Id="{253f2967-16b7-4926-8948-e00e6a6f87fb}">
      <Declaration><![CDATA[METHOD FINAL ProcessInput]]></Declaration>
      <Implementation>
        <ST><![CDATA[OnProcessInput();]]></ST>
      </Implementation>
    </Method>
    <Method Name="ProcessOutput" Id="{41595c71-5414-4593-a797-cb95863046c3}">
      <Declaration><![CDATA[METHOD FINAL ProcessOutput]]></Declaration>
      <Implementation>
        <ST><![CDATA[OnProcessOutput();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>