<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="OutputDevice" Id="{105b6dfa-d76f-4477-807a-cf1396dca32a}" SpecialFunc="None">
    <Declaration><![CDATA[(*

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2026 Oleksandr Tiutyk <trofimich@gmail.com>
| SPDX-License-Identifier: LGPL-3.0-only
| For details check: LGPL-3.0-only_

.. _LGPL-3.0-only: https://www.gnu.org/licenses/lgpl-3.0.en.html

.. </legal notes>

*)

FUNCTION_BLOCK ABSTRACT OutputDevice EXTENDS Device IMPLEMENTS IOutputDevice]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods to override" Id="{79900fc6-701a-41aa-8938-d0017f4e6cae}" />
    <Method Name="OnProcessOutput" Id="{041a293e-47c2-48cc-bc87-e724beae058b}" FolderPath="Methods to override\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT OnProcessOutput]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ProcessOutput" Id="{e860c3bd-fe5d-4af5-8b65-0b4dfced7747}">
      <Declaration><![CDATA[METHOD FINAL ProcessOutput]]></Declaration>
      <Implementation>
        <ST><![CDATA[OnProcessOutput();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>